name       : python-httpretty
version    : 1.1.3
release    : 1
source     :
    - https://github.com/gabrielfalcao/HTTPretty/archive/refs/tags/1.1.3.tar.gz : cc5d14cbabc16cfd17e0d8e3901993dab76504e76091418ba16ec4a59e1046dc
homepage   : https://github.com/gabrielfalcao/httpretty
license    : MIT
component  : programming.python
summary    : HTTP client mocking tool for Python
description: |
    HTTP Client mocking tool for Python created by Gabriel Falcão, inspired by FakeWeb. It provides a full fake TCP socket module. 
build      : |
    %python3_setup
install    : |
    %python3_install
